### PR TITLE
2544 terraform s3 create object

### PR DESCRIPTION
**Pull request by m-s-austin**
This is the new provider and accept test for preloading objects into s3 buckets. 

Usage:

```
resource "aws_s3_bucket" "b" {
    bucket = "my_tf_test_bucket"
    acl = "private"
    tags {
        Name = "My bucket"
        Environment = "Dev"
    }
    force_destroy = true
}

resource "aws_s3_bucket_object" "test_object" {
    depends_on = "aws_s3_bucket.b"
    bucket = "my_tf_test_bucket"
    key = "magic_key"
    source = "crash.log"
}
```

The acceptance test is still not working properly and I am not 100% sure why yet. I intend to get the golang debugger out and dig into it.

### CODE REVIEW

**Comment by m-s-austin** [comment]
Here is a linux binary for this version:
https://s3.amazonaws.com/ijoin_fork_terraform_distro/linux_amd64.zip

**Comment by m-s-austin** [comment]
Acceptance tests are all running again! 

```
aws_s3_bucket.object_bucket
  provider.aws
aws_s3_bucket_object.object
  aws_s3_bucket.object_bucket
provider.aws
--- PASS: TestAccAWSS3BucketObject_basic (6.00s)
PASS
ok      github.com/hashicorp/terraform/builtin/providers/aws    6.010s
```

**Comment by m-s-austin** [comment]
OS X Binaries:
https://s3.amazonaws.com/ijoin_fork_terraform_distro/darwin_amd64.zip

I have updated the binaries with the latest working changes.

**Comment by chimmelb** [comment]
+1 on the docs (they look like fine docs, if I understood Go and what you were up to)

**Comment by tehnorm** [comment]
@m-s-austin if you've not already make sure to update https://github.com/iJoinSolutions/vagrant/blob/master/ops/README.md with the new location to our build of terraform and any additional details that might be needed.

**Comment by bdesilva** [comment]
This is what I need! How do I get this build and utilize the s3 object resource?

**Pull request merged**
